version: "3"
services:
  aws-es-proxy:
    image: mario21ic/aws-es-proxy
    healthcheck:
      test: curl --fail -s http://localhost:9200/ || exit 1
      #interval: 1m30s
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      #- ./:/apps/
      - ~/.aws/credentials:/root/.aws/credentials:rw
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=AWS-ES-PROXY]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [node.role == manager]
    ports:
      - 9200:9200
    command: ./aws-es-proxy -endpoint ${ENDPOINT}

